cli:
  app_directory: apps
  base_model: apps.teams.models.BaseTeamModel
  css_framework: tailwind
  module_path: apps
  template_directory: templates
  use_teams: true
default_context:
  _pegasus_version: '2025.8'
  author_name: Wijnand
  bundler: webpack
  ci: github_actions
  css_framework: tailwind
  css_theme: default
  database: postgres
  deploy_platform: heroku
  description: This is the repo in which I will try to get Scriv working
  docker_setup: default
  domain_name: 127.0.0.1:8000
  email: wijnand@baretta.nl
  enable_github_login: n
  enable_google_login: n
  enable_twitter_login: n
  front_end_framework: htmx
  github_username: wijnandb
  include_static_files: y
  marketing_email_platform: email_octopus
  plugin_chat_mode: openai
  plugins:
  - chat
  post_process: y
  project_name: Botminds
  project_slug: botminds
  python_package_manager: uv
  standalone_front_end: none
  stripe_payment_mode: checkout
  subscription_billing_model: default
  subscription_pricing_ui: stripe_hosted
  use_2fa: y
  use_admin_docs: y
  use_ai_rules_claude: y
  use_ai_rules_cursor: y
  use_ai_rules_junie: n
  use_api_auth: n
  use_api_keys: n
  use_async: n
  use_celery: y
  use_cloud_media_storage: y
  use_dark_mode: n
  use_debug_toolbar: y
  use_docker: n
  use_ecommerce_example: n
  use_examples: n
  use_flowbite: n
  use_health_checks: y
  use_impersonation: y
  use_sentry: y
  use_shadcn: n
  use_subscriptions: y
  use_teams: y
  use_teams_example: n
  use_translations: y
  use_wagtail: y
